_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
env:
    value: CustomEnv
episodes:
    value: 1000
gamma:
    value: 0.99
hidden_dim:
    value: 56
learning_rate:
    value: 0.003
maxsteps:
    value: 100
reward_fn:
    value: utils.dense_reward
seed:
    value: 543
